version: '3.9'

services:
  app:
    build: .
    container_name: node_app
    ports:
      - "${PORT}:${PORT}"
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=${PORT}
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
    command: npm run dev

  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
